### ISSUE TITLE
Fail

### ISSUE THREAD

**Issue by Shuunen** [javierbyte/gitpage-timemachine#2]
Hi,

I tryed your app on my Windows 10 X64 environement with node v6.9.2, npm v3.10.9

```
C:\Users\me\gitpage-timemachine>node cli.js
rimraf _git
> mkdir -p pageData && git clone https://github.com/Shuunen/solitaire _git
{ Error: Command failed: mkdir -p pageData && git clone https://github.com/Shuunen/solitaire _git
A subdirectory or file pageData already exists.
Error occurred while processing: pageData.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'mkdir -p pageData && git clone https://github.com/Shuunen/solitaire _git' }
```

Because this command created a "-p" folder :

![image](https://cloud.githubusercontent.com/assets/439158/25771035/ecd6f004-3245-11e7-92a7-5bf7c96709d2.png)

I assume a problem with mkdir command param.

Edit : indeed "-p, --parents " param does exists only on unix mkdir binary

Edit 2 : second try, I edit cli.js to remove the "-p" params (2 times) and started cli again :

```
C:\Users\me\gitpage-timemachine>node cli.js
rimraf _git
> mkdir pageData && git clone https://github.com/Shuunen/solitaire _git
run http server
> cd _git && python -m SimpleHTTPServer 9142
reading commit history
Open _git folder
_git folder opened
Saving json, 20 elements

getting screenshot 1/20
getCommitScreenshot: 00173fe2089cdeadefa38727c25ae3a18cb5605a
checkoutCommit: 00173fe2089cdeadefa38727c25ae3a18cb5605a
> cd _git && git checkout 00173fe2089cdeadefa38727c25ae3a18cb5605a
getScreenshot: 00173fe2089cdeadefa38727c25ae3a18cb5605a
(node:7916) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Couldn't load url: http://localhost:9142
```

Edit 3 : I installed Python to make the "python -m SimpleHTTPServer 9142" work, this should be added in the readme as a requirement

Edit 4 : now it's nearly working, because my app is not a static index.html, I only have these kind of screenshot : 

![image](https://cloud.githubusercontent.com/assets/439158/25771145/91502954-3249-11e7-9df5-ec928095ea9b.png)

Edit 5 : I tryed with another repo of mine (https://github.com/Shuunen/flood-it) and had better results : 

![image](https://cloud.githubusercontent.com/assets/439158/25771268/4a86c510-324d-11e7-8c71-e12b9140bd60.png)

But still missing some stuff :) maybe you could add more config to define wich command to execute before capturing or delay to wait

**Comment by javierbyte** [comment]
@Shuunen thank you for the report! I made this only for unix envs, I'll try to update the code to use OS agnostic commands instead of assuming bash.

Most of the screenshot related config is here https://github.com/javierbyte/gitpage-timemachine/blob/master/cli.js#L20, maybe I can add a config option to merge with the default pageres config. In the mean time you can edit that file :)
